# Generated by Django 3.2.18 on 2023-02-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deliverability", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedAccount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        help_text="Seed account ID.", primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(help_text="Username of the seed.", max_length=255)),
                ("password", models.CharField(help_text="Password of the seed.", max_length=255)),
                (
                    "dateadded",
                    models.DateTimeField(
                        blank=True, db_column="dateAdded", help_text="Timestamp added.", null=True
                    ),
                ),
                (
                    "lastleased",
                    models.DateTimeField(
                        blank=True,
                        db_column="lastLeased",
                        help_text="Last time account leased.",
                        null=True,
                    ),
                ),
                (
                    "lastpulled",
                    models.DateTimeField(
                        blank=True,
                        db_column="lastPulled",
                        help_text="Last time pulled account.",
                        null=True,
                    ),
                ),
                (
                    "enabled",
                    models.IntegerField(blank=True, help_text="Is account enabled?", null=True),
                ),
                (
                    "status",
                    models.IntegerField(
                        blank=True, help_text="Status of the seed account.", null=True
                    ),
                ),
                ("priority", models.IntegerField(help_text="Is the seed higher priority?")),
                ("reserved", models.IntegerField(help_text="Is the seed account reserved?")),
                (
                    "emailaddress",
                    models.CharField(
                        blank=True,
                        db_column="emailAddress",
                        help_text="Email address of the seed account.",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "timestamp_update",
                    models.DateTimeField(
                        help_text="Last time seed account information updated timestamp."
                    ),
                ),
                (
                    "connection_error_count",
                    models.IntegerField(
                        help_text="Number of errors while processing the seed account."
                    ),
                ),
            ],
            options={
                "db_table": "ibx_seed_accounts",
                "managed": False,
            },
        ),
    ]
